Smarter merging of Person metadata
Materials-Data-Science-and-Informatics/somesy pull request #20
Opened 2023-06-21 11:21 UTC by apirogov

Minor:

* moved and renamed some things
* `path.exists() -> path.is_file()` (exists also accepts a directory)

Major:
* refactored and streamlined project writers

2023-06-21 13:44 UTC, apirogov commented
I think to avoid pains going forward, maybe you should first merge this, then I start working on the Person merge @mustafasoylu

2023-06-22 06:36 UTC, mustafasoylu commented on src/somesy/core/writer.py
> +        (e.g. if everything relevant is in some suboject).
typo: subobject

2023-06-22 06:36 UTC, mustafasoylu commented on src/somesy/core/writer.py
> +        (e.g. if everything relevant is in some suboject).
typo: subobject

2023-06-22 06:53 UTC, mustafasoylu requested changes
You made an incredible job here! I took a model where I separated functions into files, but this seems tidier. Just found a typo, I will approve right after that.

2023-06-22 08:15 UTC, mustafasoylu approved these changes
LGTM

2023-06-22 08:15 UTC, merged